### ISSUE TITLE
not sending with connect() 

### ISSUE THREAD

**Issue by serkandaglioglu** [pallets-eco/flask-mail#142]
If send with connect() it throws error
```
with g.mail.connect() as mailConn:
    g.appEmail.send(
          title=form.mail_subject.data,
          body="",
          html= form.mail_body.data,
          recipients = emails,
          mailConn = mailConn
      )
```
ERROR : 
```
ERROR:root:Connection unexpectedly closed: [SSL: WRONG_VERSION_NUMBER] wrong ver
sion number (_ssl.c:1754)
Traceback (most recent call last):
  File "D:\Documents\Private\Python\macbook\flask\intorna\intorna\api\modules\ma
il\controllers\admin_controller.py", line 140, in post
    mailConn = mailConn
  File "D:\Documents\Private\Python\macbook\flask\intorna\env\lib\site-packages\
flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "c:\python27\Lib\smtplib.py", line 772, in quit
    res = self.docmd("quit")
  File "c:\python27\Lib\smtplib.py", line 394, in docmd
    return self.getreply()
  File "c:\python27\Lib\smtplib.py", line 365, in getreply
    + str(e))
SMTPServerDisconnected: Connection unexpectedly closed: [SSL: WRONG_VERSION_NUMB
ER] wrong version number (_ssl.c:1754)
Exception in thread Thread-3:
Traceback (most recent call last):
  File "c:\python27\Lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\python27\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "D:\Documents\Private\Python\macbook\flask\intorna\intorna\api\libraries\
app_email.py", line 38, in send
    mailConn.send(msg)
  File "D:\Documents\Private\Python\macbook\flask\intorna\env\lib\site-packages\
flask_mail.py", line 192, in send
    message.rcpt_options)
  File "c:\python27\Lib\smtplib.py", line 733, in sendmail
    (code, resp) = self.mail(from_addr, esmtp_opts)
  File "c:\python27\Lib\smtplib.py", line 481, in mail
    return self.getreply()
  File "c:\python27\Lib\smtplib.py", line 365, in getreply
    + str(e))
SMTPServerDisconnected: Connection unexpectedly closed: [SSL: WRONG_VERSION_NUMB
ER] wrong version number (_ssl.c:1754)
```

But if I send like that it sent successfully
```
g.appEmail.send(
        title=form.mail_subject.data,
        body="",
        html= form.mail_body.data,
        recipients = emails
    )
```

My mail config

```
MAIL_SERVER=''
MAIL_PORT=587
MAIL_USERNAME = ''
MAIL_PASSWORD = ''
MAIL_DEBUG = False
MAIL_SUPPRESS_SEND = False
MAIL_USE_SSL=False
MAIL_USE_TLS=True
```

My email class method

```
@async
def send(self, title="", body="", html="",recipients=[], fromEmail=None,fromName=None,mailConn = None):

    with self.app.app_context():
        mailConn = mailConn if mailConn is not None else self.mail        
        recipients = recipients if type(recipients)==list else [recipients]

        fromName = fromName if fromName is not None else self.app.config["MAIL"].get("from_name")
        fromEmail = fromEmail if fromEmail is not None else self.app.config["MAIL"].get("from")

        msg = Message(title, sender=(fromName, fromEmail), recipients=recipients)
        msg.body = body
        msg.html = html
        mailConn.send(msg)

```

**Comment by michaelbukachi** [comment]
Were you able to solve this?

**Comment by davidism** [comment]
I can't reproduce this issue.
