### ISSUE TITLE
AttributeError("'unicode' object has no attribute 'send'",)

### ISSUE THREAD

**Issue by kenzhaoyihui** [pallets-eco/flask-mail#159]
Send an async email with celery:

here is my code:
```
@celery.task
def send_async_email(to):
    """Background task to send an email with Flask-Mail."""
    subject = "Hello from me"
    sender = app.config['MAIL_DEFAULT_SENDER']
    recipients = [to]
    msg = Message(subject, sender=sender, recipients=recipients)
    msg.body = 'This is a test email sent from a background Celery task.'
    with app.app_context():
        mail.send(msg)
```

Here is the celery console:

[2018-03-15 17:59:24,507: ERROR/ForkPoolWorker-1] Task app.send_async_email[60aefd91-8683-4282-8a77-0135b0c60b6c] raised unexpected: AttributeError("'unicode' object has no attribute 'send'",)
Traceback (most recent call last):
  File "/home/yzhao_sherry/work/venv/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/yzhao_sherry/work/venv/lib/python2.7/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/yzhao_sherry/work/venv/pypro/flask-celery-example/app.py", line 107, in send_async_email
    }
  File "/home/yzhao_sherry/work/venv/lib/python2.7/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
AttributeError: 'unicode' object has no attribute 'send'

**Comment by wlach** [comment]
I suspect this was user error. Feel free to open a question in discussions if you want to debug stuff.
