### ISSUE TITLE
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by zurgeg** [pallets-eco/flask-mail#180]
I can't send mail from my app because I am stopped by this:
```
[2020-02-28 18:38:38,891] ERROR in app: Exception on /email [GET]
Traceback (most recent call last):
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\zurgE\OneDrive\Documents\Graff Family WebServer\app\routes.py", line 147, in email
    flaskmail.send(msg)
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 307, in _get_socket
    self.source_address)
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
127.0.0.1 - - [28/Feb/2020 18:38:38] "GET /email HTTP/1.1" 200 -
127.0.0.1 - - [28/Feb/2020 18:38:39] "GET /favicon.ico HTTP/1.1" 200 -

C:\Users\zurgE\OneDrive\Documents\Graff Family WebServer>python public.py
Getting App
Graff Family WS 1.0
Loading application
Handing Control to Routing
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[2020-02-28 18:47:42,993] ERROR in app: Exception on /email [GET]
Traceback (most recent call last):
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\zurgE\OneDrive\Documents\Graff Family WebServer\app\routes.py", line 147, in email
    flaskmail.send(msg)
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 307, in _get_socket
    self.source_address)
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\Users\zurgE\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
```
My Anti-Virus is Norton 360 Home and I am running Windows 10 Pro.
My mail server is self-hosted on my website and at ```mail.graffbt.com:465```

Can anyone fix my problem?
Thanks in advance.

**Comment by davidism** [comment]
I can't reproduce this issue. This would presumably be an issue to report to Python's smtplib if you can produce a minimal reproducible example.
