### ISSUE TITLE
Incorrect handling of email.message.Message in Connection.send()

### ISSUE THREAD

**Issue by yegle** [pallets-eco/flask-mail#64]
The current logic in `flask_mail.Connection.send()` to convert `flask_mail.Message` to a string then pass to `SMTP.sendmail` is incorrect. And there's no test that actually cover the `SMTP.sendmail` function.

`smtplib` in >= Python3.2 comes with a [`SMTP.send_message`](https://github.com/python/cpython/blob/master/Lib/smtplib.py#L791) function, which contains the correct logic to convert a `email.message.Message` to a byte string that `SMTP.sendmail` accept.

Sample code to reproduce:

```
from __future__ import (unicode_literals, absolute_import,
                        division, print_function)

from MY_PROJECT import app        
from flask.ext.mail import Mail, Message

mail = Mail(app)         

text = '测试'            

subject = "Your Weibo content request"

with mail.connect() as conn:      
    recipients = ['user@example.com']
    msg = Message(subject, recipients=recipients,
                  sender="no-reply@localhost")
    msg.body = text      
    conn.send(msg) 
```

Corresponding traceback

```
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    conn.send(msg)
  File "/data/web/cgi-bin/venv/lib/python3.4/site-packages/flask_mail.py", line 168, in send
    message.as_string())
  File "/data/web/cgi-bin/python-3.4.0/lib/python3.4/smtplib.py", line 752, in sendmail
    msg = _fix_eols(msg).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 284-285: ordinal not in range(128)
```

**Comment by garni-kh** [comment]
hi i have same issue now, same problem how can i solved it in py3 please help
